import argparse
import os
import datetime
from .data import load_data
from .model import GPTLanguageModel
from .utils import set_seed, generate_text
from .train import initialize_idl_heads, train_model


def parse_args():
    parser = argparse.ArgumentParser(description="Train, evaluate and generate text with GPT implicit models.")
    
    # device id and seed
    parser.add_argument("--device", type=int, default=0, help="Specify the device id (e.g., 0 for cuda:0)")
    parser.add_argument("--seed", type=int, default=0, help="Random seed for reproducibility")
    
    # dataset and training configs
    parser.add_argument("--dataset", type=str, required=True, help="Dataset")
    parser.add_argument("--batch_size", type=int, default=64, help="Training batch size")
    parser.add_argument("--block_size", type=int, default=256, help="Size of data blocks")
    parser.add_argument("--max_iters", type=int, default=30000, help="Max training iterations")
    parser.add_argument("--eval_interval", type=int, default=500, help="Interval for evaluation")
    parser.add_argument("--learning_rate", type=float, default=1e-4, help="Learning rate for optimizer")
    parser.add_argument("--eval_iters", type=int, default=200, help="Number of iterations for evaluation")
    parser.add_argument("--n_embd", type=int, default=384, help="Embedding size")
    parser.add_argument("--n_head", type=int, default=2, help="Number of attention heads")
    parser.add_argument("--n_layer", type=int, default=2, help="Number of layers")
    parser.add_argument("--dropout", type=float, default=0.2, help="Dropout rate")
    
    # IDL configs
    parser.add_argument("--fixed_point_iter", type=int, default=2, help="Fixed point iteration count")
    parser.add_argument("--enforce_structure_IDL", action="store_true", help="Enforce structured IDL model")
    parser.add_argument("--attention_version", type=str, default="softmax", help="Attention mechanism version")
    parser.add_argument("--max_new_tokens", type=int, default=100, help="Max new tokens for generation")
    parser.add_argument("--is_low_rank", action="store_true", help="Low-rank approach for implicit model")
    parser.add_argument("--rank", type=int, default=1, help="Rank k of the low-rank approach")
    
    return parser.parse_args()


def main():
    """
    Main function to initialize models, train, evaluate and generate text.
    """

    args = parse_args()
    set_seed(args.seed)
    device = f"cuda:{args.device}"
    
    # log file
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
    log_dir = os.path.join(base_dir, 'results', f"im_attention_{args.dataset}")
    os.makedirs(log_dir, exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    log_file = os.path.join(log_dir, f"{timestamp}.log")
    
    # Load data
    train_data, val_data, vocab_size, additional_data = load_data(args)
    data = {"train": train_data, "val": val_data}

    # Initialize implicit model
    idl_model = GPTLanguageModel(
        vocab_size, 
        args.n_embd, 
        args.block_size, 
        args.n_layer, 
        args.n_head, 
        args.dropout
    )
    initialize_idl_heads(args, idl_model)
    idl_model.to(device)
    
    # train implicit model
    train_model(args, idl_model, data, device, log_file)
    
    # text generated by IDL model
    generated_text = generate_text(args, idl_model, additional_data, device)
    with open(log_file, 'a') as f:  
        f.write(f"Generated text with the trained IDL model: {generated_text}\n")
    print(f"Generated text with the trained IDL model: {generated_text}")
    
    
if __name__ == "__main__":
    main()